### ISSUE TITLE
Cython version?

### ISSUE THREAD

**Issue by mfeurer** [scikit-learn-contrib/project-template#13]
I just wanted to know if there is a reason why you specify a cython version? Are there any problems using newer versions than the ones proposed? If no, do you use them for backwards compability?

**Comment by MechCoder** [comment]
sklearn requires at least Cython Version 0.21 https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/cythonize.py#L60

**Comment by mfeurer** [comment]
Thanks for your answer. I was asking because one project I want to use this in requires a higher version number. Thus, I wondered why the version number of cython is hardcoded at all and whether there can be any trouble removing this.

**Comment by mblondel** [comment]
Pull-request welcome :)

**Comment by mfeurer** [comment]
I'm not sure if I get what should be in such a pull request.
- explanation of the version number?
- same version number for both python versions?

**Comment by glemaitre** [comment]
We should actually not have any Cython in the template if people are doing pure Python package. They will install a wheel from scikit-learn and they don't have to build scikit-learn. I would simplify this part.
