### ISSUE TITLE
Add appveyor CI

### ISSUE THREAD

**Issue by mblondel** [scikit-learn-contrib/project-template#14]
Here are the files used in scikit-learn and lightning:
https://github.com/scikit-learn/scikit-learn/blob/master/appveyor.yml
https://github.com/scikit-learn-contrib/lightning/blob/master/appveyor.yml

**Comment by vighneshbirodkar** [comment]
I am currently working on this

**Comment by vighneshbirodkar** [comment]
Deployed on my own fork
https://ci.appveyor.com/project/vighneshbirodkar/project-template

I am waiting for some pointers in https://github.com/ogrisel/wheelhouse-uploader/issues/16 to proceed.

**Comment by fabianp** [comment]
Anything in particular that you need help on?

**Comment by vighneshbirodkar** [comment]
@fabianp The `wheelhouse_uploader` module cannot correctly upload this package because of bug in its filename parsing code.

**Comment by ogrisel** [comment]
wheelhouse-uploader 0.9.3 has been released with @vighneshbirodkar's fix for parsing the filenames.

**Comment by jnothman** [comment]
Fixed by #22
