### ISSUE TITLE
Extra dependencies in section "Modifying the Documentation"

### ISSUE THREAD

**Issue by ghost** [scikit-learn-contrib/project-template#24]
In the readme file, section "Modifying the Documentation", instead of:
`pip install sphinx matplotlib sphinx-gallery
`
perhaps it should be:
`pip install sphinx matplotlib sphinx-gallery numpydoc sphinx_rtd_theme`

What do you think?

**Comment by vighneshbirodkar** [comment]
Thank you, I will submit a PR for the change soon.
