### ISSUE TITLE
pngmath vs. imgmath

### ISSUE THREAD

**Issue by ghost** [scikit-learn-contrib/project-template#26]
When building the documentation with `make html` I receive the following warning:
`sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.`

What do you think, should we adjust `doc/conf.py` to use the newer extension? 
Currently, I am not aware of any negative impact.

Running `Sphinx v1.4.5`.

**Comment by TomDLT** [comment]
solved in ac1f099d2d29d033329782d3776e681e8a41623e
Thanks for the report.
