### ISSUE TITLE
test_estimator not valid for vectorizers

### ISSUE THREAD

**Issue by ysig** [scikit-learn-contrib/project-template#29]
We are currently developing a transformer compatible with sk-learn that behaves
as a vectorizer for graph type object. The test estimator method injects arrays of
n by m which are not valid to our current input.Tfidf vectorizer supports also a kind
o input that is not an array of n by m features, but rather a vector of strings.
Can the check_estimator constraints be softened for a vectorizer type transformer?

https://github.com/scikit-learn-contrib/project-template/blob/ac1f099d2d29d033329782d3776e681e8a41623e/skltemplate/tests/test_common.py#L7

**Comment by agramfort** [comment]
send us a PR

**Comment by ysig** [comment]
Ok, the personal repo is the link that follows. The library is not yet mature, but the essential part is there and concerns the input form of the graph_kernel file. It is just an iterable (a vector) of objects (in our case a list of lists) where inside each sub-list we expect as elements a graph type input and optionally graph labels. Init function is used to set the kernel function applied in "transform".
https://github.com/ysig/GraKeL
https://github.com/ysig/GraKeL/blob/master/grakel/graph_kernels.py

**Comment by glemaitre** [comment]
Actually this should be reported to scikit-learn since that we want the `check_estimator` to be flexible enough.
