### ISSUE TITLE
sphinx gallery cross-links with project objects not present in generated examples

### ISSUE THREAD

**Issue by agramfort** [scikit-learn-contrib/project-template#32]
for example TemplateTransformer is not clickable in 

http://contrib.scikit-learn.org/project-template/auto_examples/plot_transformer.html#sphx-glr-auto-examples-plot-transformer-py

**Comment by ysig** [comment]
This line: `autosummary_generate = True` is missing on (say) line 68, inside the [conf.py](https://github.com/scikit-learn-contrib/project-template/blob/master/doc/conf.py#L68) file.

Probably, forgotten after copy-pastes from the original sklearn  [conf.py](https://github.com/scikit-learn/scikit-learn/blob/master/doc/conf.py#L62) file, as there exists
nothing relevant as a comment, while at the same time `'sphinx_gallery.gen_gallery'`
exists inside `extensions` *list*.
