### ISSUE TITLE
Simplify CI template

### ISSUE THREAD

**Issue by rth** [scikit-learn-contrib/project-template#40]
To follow up on @glemaitre's comment in https://github.com/scikit-learn-contrib/project-template/pull/31#issuecomment-422558477

The current CI template is somewhat outdated and a bit complex. A few thoughts on what could be simplified,
 - drop circle CI altogether in favor of using readthedocs.org for the documentation: the latter requires much technical effort to setup and maintain. @glemaitre can share his experience with imbalance-learn
 - Appveyor: I find spotlight's setup fairly clean https://github.com/maciejkula/spotlight/blob/master/appveyor.yml  some things might be adapted from there. Maybe drop the wheel uploading: for maintainers new to Appveyor this may be a bit too much, and it can always be added subsequently in the project.

**Comment by glemaitre** [comment]
I will update the template:

TODO:

- [ ] Simplify the setup.py file
- [ ] Simplify Travis CI configuration file
- [ ] Simplify AppVeyor configuration file
- [ ] Update Circle CI to version 2.0
- [ ] Move the documentation build to readthedocs.
- [ ] Update and simplify the README.rst
- [ ] Create a pip package

**Comment by rth** [comment]
Also maybe https://github.com/audreyr/cookiecutter could help achieve this project's objectives? There are some templates more focused on scientific packages from what I heard. Though I have never used it personally.
