### ISSUE TITLE
GitHub bot applying the template to the projects it is used in

### ISSUE THREAD

**Issue by KOLANICH** [scikit-learn-contrib/project-template#45]
When some goodie is added to the template, it would be nice to add it to all the projects using the template.

When something worth to add to the forks is added to master branch of this repo the bot should
1. create a patch with `git format-patch`
2. walk the list of known projects in this repo in some text format. resolve their names in order to handle renamings
3. clone each one and try to apply the patch
4. if the patch is applied successfully, create a PR to that repo

**Comment by glemaitre** [comment]
I think that we will go simple. Having a project template that is up-to-date would be a reasonable target :)
