### ISSUE TITLE
Move project to scikit-learn-contrib

### ISSUE THREAD

**Issue by mblondel** [scikit-learn-contrib/project-template#5]
Hi! 

Very nice project. We recently created the scikit-learn-contrib organization on github and I think it would be the perfect home for this project. Would you be willing to move your project there? If it's ok with you, I will give you membership to the organization and then you can transfer this repo to the organization.

https://github.com/scikit-learn-contrib

A possibly more explicit name for the repo would be just "project-template" although I am fine if you prefer to keep the current name.

CC @amueller @jnothman

**Comment by vighneshbirodkar** [comment]
I am fine with any name as long as the naming js consistent throughout the project. If we decide to call it `project-template`, I would prefer to rename the underlying estimator to `TemplateEstimator`. 

Let me know your thoughts.

**Comment by amueller** [comment]
yeah sounds good.

**Comment by amueller** [comment]
That facilitates also more centralized discussion.
@vighneshbirodkar can you point me to your discussion with @jnothman ?

**Comment by vighneshbirodkar** [comment]
@amueller 
https://github.com/vighneshbirodkar/sklearn-stub/pull/4 
and
https://github.com/scikit-learn/scikit-learn/issues/4473

**Comment by jnothman** [comment]
I had thought this would move to scikit-learn project, where it would be
more visible if s.l.c. takes off.

**Comment by amueller** [comment]
@jnothman you mean this would move to the scikit-learn org and no the scikit-learn-contrib org? I kinda feel the same, though I wasn't sure.

**Comment by MechCoder** [comment]
I also feel it might be better to move it to scikit-learn!

**Comment by mblondel** [comment]
But the goal is to encourage people to create projects in scikit-learn-contrib! And we can use contrib.scikit-learn.org/project-template/ to host the documentation demo.

**Comment by jnothman** [comment]
I think that's a bit moot, and it's a bit arbitrary. I guess I'd be happy
to see project-template there in scikit-learn-contrib's repository
listing... but assuming it'll be infrequently updated, it won't appear near
the top!

**Comment by mblondel** [comment]
I think the best way to give visibility to project-template is to advertise it on scikit-learn.org and / or contrib.scikit-learn.org.

**Comment by jnothman** [comment]
Indeed. So then I'm happy to toss a coin, or go with whoever is pushiest

**Comment by vighneshbirodkar** [comment]
My suggestion would be to leave it in `scikit-learn` (for visibility) and have a ~~form~~fork of it in the scikit-learn-contrib organization. Forgive me, but I am not sure what the purpose behind the contrib organization is ? What is `scikit-learn-contrib` facilitating that `scikit-learn` cannot ?

**Comment by mblondel** [comment]
The purpose of the contrib org is to gather quality third-party projects compatible with scikit-learn. I guess we created a different org to separate third-party projects from the official scikit-learn package.

@GaelVaroquaux @agramfort @vene @glouppe @ogrisel @fabianp @jakevdp
Any opinion whether the project template should go to scikit-learn or scikit-learn-contrib org?

**Comment by jnothman** [comment]
I.e. scikit-learn-contrib will house relatively mature instantiations of
this template.

**Comment by agramfort** [comment]
+1 for putting it in scikit-learn-contrib

**Comment by MechCoder** [comment]
Why not do both?

Have the actual template in scikit-learn and the mature projects in scikit-learn-contrib that use the template.

Also what are the hard requirements for a project to be listed in `scikit-learn-contrib`, if any?

**Comment by jakevdp** [comment]
To me it makes sense to put it in scikit-learn-contrib.

**Comment by GaelVaroquaux** [comment]
+1 for putting in in scikit-learn-contrib.

**Comment by vighneshbirodkar** [comment]
I guess the consensus here is to put it in `scikit-learn-contrib`. I will go ahead and change the project name to `project-template` and change the estimators name to `template.TemplateEstimator`.

**Comment by mblondel** [comment]
@vighneshbirodkar I sent you an invitation to become a member of scikit-learn-contrib. Thanks in advance for the refactoring!

**Comment by vighneshbirodkar** [comment]
@mblondel I have done the refactoring. The main changes are
for installing

```
$ pip install sklearn-template
```

for executing

```
>>> from template import TemplateEstimator
```

**Comment by amueller** [comment]
I think `template` is a bad top-level module name, as it is very generic. It should probably be skltemplate or something like that.

**Comment by vighneshbirodkar** [comment]
@amueller Done. It is `skltemplate` now

**Comment by amueller** [comment]
thanks :)

**Comment by vighneshbirodkar** [comment]
Can I move this to SLC now ?

**Comment by amueller** [comment]
yes

**Comment by vighneshbirodkar** [comment]
@amueller Where do you want the docs to be hosted ?

**Comment by amueller** [comment]
a gh-pages branch?

**Comment by vighneshbirodkar** [comment]
@amueller Yes, but the the URL ? `scikit-learn-contrib.github.io/docs`?

**Comment by amueller** [comment]
it will be `scikit-learn-contrib.github.io/sklearn-template`, right?

**Comment by mblondel** [comment]
Please use scikit-learn-contrib.github.io/project-template.

**Comment by vighneshbirodkar** [comment]
@mblondel It is live here
http://contrib.scikit-learn.org/project-template/

Although as it currently stands, all source files are also being hosted on the gh-pages branch. Is that a problem ? 
https://github.com/scikit-learn-contrib/project-template/tree/gh-pages

**Comment by mblondel** [comment]
Why is the branch needed?

**Comment by vighneshbirodkar** [comment]
@mlblondel for the website ?

**Comment by mblondel** [comment]
Sorry, I thought you had uploaded the website here:
https://github.com/scikit-learn-contrib/scikit-learn-contrib.github.io
