### ISSUE TITLE
how to run doctests?

### ISSUE THREAD

**Issue by amueller** [scikit-learn-contrib/project-template#51]
How are doctests in the docs run here? Are they run on CI? I think they should be.

**Comment by hayesall** [comment]
I was looking through some of the examples and noticed this too.

According to the documentation: doctests seem like they should be set up through *CircleCI*:

https://github.com/scikit-learn-contrib/project-template/blob/e588f28c91b3664bc4fc3cc6ae8b38407e319624/doc/quick_start.rst#L109-L111

However, the pipeline in `.circleci/config.yml` currently performs:

https://github.com/scikit-learn-contrib/project-template/blob/e588f28c91b3664bc4fc3cc6ae8b38407e319624/.circleci/config.yml#L20-L21

---

Normally I would expect doctests to run with `make doctest`, producing something like the following:

```bash
$ make doctest

# -snip-
Doctest summary
===============
   38 tests
    0 failures in tests
    0 failures in setup code
    0 failures in cleanup code
build succeeded.
```

If any doctests fail, `make doctest` should return 2:

```bash
$ make doctest
# -snip-
Doctest summary
===============
   38 tests
    1 failure in tests
    0 failures in setup code
    0 failures in cleanup code
build finished with problems.

$ echo $?
2
```

---

Seems like this should be a fairly easy fix. I'll experiment a bit and submit a pull request in an hour or so.
