### ISSUE TITLE
License when using this template

### ISSUE THREAD

**Issue by vicramr** [scikit-learn-contrib/project-template#52]
This repo includes a `LICENSE` file which says at the top: 
```
Copyright (c) 2016, Vighnesh Birodkar and scikit-learn-contrib contributors
```
I have several questions about the rules regarding a new project I'm creating with this template.
* For my project, can I use my own license or do I have to keep the existing license?
* `project-template` has a 3-Clause BSD license. If I use my own license, does it have to also be BSD 3-Clause or can it be different (e.g. Apache 2.0, MIT)?
* Do I have to credit scikit-learn-contrib and/or Vighnesh Birodkar anywhere in my repo/source code?

**Comment by rth** [comment]
> For my project, can I use my own license or do I have to keep the existing license?

I'm not familiar with all the intricacies of licensing but as far as I know, yes, you can. One condition is,

> * Neither the name of project-template nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

See e.g. https://opensource.stackexchange.com/questions/304/can-i-take-bsd-licensed-code-and-distribute-it-under-gpl

> project-template has a 3-Clause BSD license. If I use my own license, does it have to also be BSD 3-Clause or can it be different (e.g. Apache 2.0, MIT)?

No, you can use any other license. Again there might be some licensing complexities, but in any case scikit-learn-contrib developers won't have an issue with it I think.

> Do I have to credit scikit-learn-contrib and/or Vighnesh Birodkar anywhere in my repo/source code?

No you don't have to, though mentioning it somewhere (e.g. as a code comment in setup.py) could be nice.
