### ISSUE TITLE
Can't import skltemplate in doc/conf.py

### ISSUE THREAD

**Issue by oulenz** [scikit-learn-contrib/project-template#55]
PR https://github.com/scikit-learn-contrib/project-template/pull/41 introduced `from skltemplate import __version__` to `doc/conf.py`. But now when I run `make html` this gives me `ModuleNotFoundError: No module named 'skltemplate'`. So I was wondering what the intended workflow is for building the docs.

EDIT: I realise now that none of the docstring imports for the api documentation work either. So the intention must be for `skltemplate` to be in the python path when the documentation is generated, but how?

**Comment by rickvanveen** [comment]
You can install you package by going into the folder containing the `setup.py` file and running `pip install -e . `, where the ` . ` references the current folder. After this the module is available on the python path and the `make html` will be able to find it. 

I don't know if this is the prefered or intended way of dealing with this (as it is not mentioned in the [quick start guide](https://sklearn-template.readthedocs.io/en/latest/quick_start.html)), but it seems reasonable.

**Comment by rth** [comment]
The previous comment by @rickvanveen should address this issue. Closing. Thanks!
