### ISSUE TITLE
Use setuptools_scm

### ISSUE THREAD

**Issue by MuellerSeb** [scikit-learn-contrib/project-template#59]
It would be nice, if this template could use `setuptools_scm` for automated versioning:
https://github.com/pypa/setuptools_scm

**Comment by rth** [comment]
Assuming that we add `pyproject.toml` with it as a build dependency (cf e.g. https://github.com/scikit-learn-contrib/scikit-learn-extra/pull/51) so that users don't have to manually install it, we could consider it. Pull Request would be welcome.
