### ISSUE TITLE
check_estimator

### ISSUE THREAD

**Issue by RomainBrault** [scikit-learn-contrib/project-template#6]
Hello,

I'm currently developing a library thanks to your project, and I notice that in sklearn 0.17 (as seen in the requirements), check_estimator should take a class instance. Whereas in master it should take a class object:

In version 0.17.x

```
    Parameters
    ----------
    Estimator : class
        Class to check.
    """
    name = Estimator.__class__.__name__
```

In master

```
    Parameters
    ----------
    Estimator : class
        Class to check. Estimator is a class object (not an instance).
    """
    name = Estimator.__name__
```

Any idea on how to handle these different cases?

**Comment by vighneshbirodkar** [comment]
@RomainBrault You can use an if else statement based on the version number. I can't think of a clearner way to do it.

Thoughts @mblondel  ?

**Comment by mblondel** [comment]
We typically try to maintain backward compatibility for two releases so this seems like a bug. 

@amueller Would it be possible to support both classes and instances for two releases?

**Comment by amueller** [comment]
From the discussion, it seems the 0.17 version is a bug and didn't work. All the checks expect a class object, not an instance.

**Comment by RomainBrault** [comment]
@vighneshbirodkar Yes, it's what I did, but It looks a bit hackish to do it at user's level.

Anyway If I pass an instantiation of the object in 0.17, check_estimator only uses its class name. I think
it's actually useful if the check is done at the class level: one can do `check_estimator(self)` instead of `check_estimator(self.__class__).`

However if not applying on self, the code in master looks more natural to me (no need to (default) construct the estimator). I would be in favour of supporting both.

**Comment by azrdev** [comment]
In the meantime (I'm looking at current sklearn 0.19.1) `check_estimator` can work with an instance or class, so this can be closed.
