### ISSUE TITLE
Make circle-ci build fail if deployment to gh-pages fails

### ISSUE THREAD

**Issue by mfeurer** [scikit-learn-contrib/project-template#7]
Currently, a circle-ci build is marked as succesful, although the deployment to gh-pages did not work. You can see a failing example [here](https://circleci.com/gh/openml/openml-python/44)

**Comment by vighneshbirodkar** [comment]
@mfeurer Thanks for pointing this out. I am just curious, how did you use this project ? Did you fork/clone ? Or just used the files directly.

**Comment by mfeurer** [comment]
We've already had a project which uses travis-ci and readthedocs, therefore I just copied the ci related files.

**Comment by vighneshbirodkar** [comment]
@mfeurer You take the changes from #8 to fix the issue

**Comment by mfeurer** [comment]
In my opinion, this can be closed.

**Comment by vighneshbirodkar** [comment]
@MechCoder Can you take a look at this and merge ?

**Comment by vighneshbirodkar** [comment]
Closed by #8
