### ISSUE TITLE
Does Templates supports pandas output 

### ISSUE THREAD

**Issue by RahulDas-dev** [scikit-learn-contrib/project-template#75]
There are a lot of changes in scikit-learn 1.2.0 where it supports pandas output for all of the transformers but how can I use it in a custom transformer template ?

Does this features is available for custom transformer template ??

**Comment by glemaitre** [comment]
The template will support pandas output. You only need to inherit from `TransformerMixin` and you will get his feature.

There is more info here: https://scikit-learn.org/dev/developers/develop.html#developer-api-for-set-output
