### ISSUE TITLE
Button links in documentation index redirects to wrong pages

### ISSUE THREAD

**Issue by gtauzin** [scikit-learn-contrib/project-template#83]
Hi,

Going through the published documentation at https://contrib.scikit-learn.org/project-template/, I have noticed that two of the button links redirects toward pages of the matplotlib and pandas documentation:

- The Getting started button [To the getting started guideline](https://matplotlib.org/stable/users/explain/quick_start.html#quick-start) redirects to https://matplotlib.org/stable/users/explain/quick_start.html#quick-start
- The API reference button [To the reference guide](https://pandas.pydata.org/pandas-docs/stable/reference/index.html#api) redirects to https://pandas.pydata.org/pandas-docs/stable/reference/index.html#api

Note that, he "Next" links at the bottom right of the pages directs to the correct pages and the two other buttons work as intended.

The same problem appears if I build the doc locally. However, if I comment out the matplotlib and pandas entry in the intersphinx_mapping dict in `doc/conf.py` and build the doc again, those two buttons are no longer clik-able. I am no sphinx expert, but it seems sphinx is not able to link the buttons to the html conversion of `quick_start.rst` and `api.rst` and ends up using intersphinx to generate those links.

**Comment by glemaitre** [comment]
This is interesting. Let me switch to the sphinx-design that should be easier to read actually.

**Comment by glemaitre** [comment]
Interestingly, I forgot to add the sphinx reference in the local doc `.. _quick_start:` and `.. _api:` and thus intersphinx was linking to the symbols of external documentation that matched.
