### ISSUE TITLE
Using `_validate_data` in custom estimators

### ISSUE THREAD

**Issue by SimonBlanke** [scikit-learn-contrib/project-template#88]
Hello,

after going through the [template-file](https://github.com/scikit-learn-contrib/project-template/blob/main/skltemplate/_template.py) I noticed, that the method `_validate_data` was used for the templates for custom estimators. The underscore prefix suggests, that it is not a public method and therefore might be subject to change in the future (even in non-major version changes).

From my experience using `_validate_data` makes it easy to pass the `check_estimator`-method from `sklearn.utils.estimator_checks`. However I am not comfortable to use a "backend"-method, that might not exist in the future. 

So how is it save to use this method? Should a user use `_validate_data`, when implementing a custom estimator?

**Comment by glemaitre** [comment]
So we are in our way to make a proper public developer API.

From scikit-learn 1.6, `_validate_data` will be changed by a public function called `validate_data`: https://scikit-learn.org/dev/modules/generated/sklearn.utils.validation.validate_data.html#sklearn.utils.validation.validate_data to acknowledge that this is not a private function.

So in the meanwhile, it means that the code should look like:

```python
if hasattr(self, _validate_data):
    X, y = self._validate_data(X, y, ...)
else:
    X, y = validate_data(self, X, y, ...)
```

In the future, we will therefore make sure to announce through deprecation whatever changes that is happening in this function.

**Comment by SimonBlanke** [comment]
Thank you for the explanation! I will adapt my code accordingly.
